import React from 'react'
import PropTypes from 'prop-types'
import Helmet from 'react-helmet'
import {StaticQuery, graphql} from 'gatsby'
import {Link} from 'gatsby'
import Header from './header'
import ImageUpload from './ImageUpload'
import Footer from './footer'
import './css/layout.css'
import { Card, CardImg, CardTitle, CardText, CardBody, Breadcrumb, BreadcrumbItem } from 'reactstrap';
